config/routes.rb
Rails.application.routes.draw do

  resources :relationships
  #用户管理，活动管理
  get 'admin/show'
  get 'admin/activityshow'
  get 'admin/activity_allow'
  get 'admin/activity_fail'
  get 'admin/myActivity'
  get 'admin/createMyActivity'
  get 'admin/personal'
  get 'admin/delete'
  get 'admin/update'
  get 'sessions/new'
  resources :users

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/schoolSelect'
  get 'static_pages/filterBySelect'
  # 根路由
  root 'static_pages#home'
  # 具名路由
  get  '/help',    to: 'static_pages#help'
  get  '/schoolSelect',  to: 'static_pages#schoolSelect'
  get "/search" => "search#index", :as => "search"
  resources :activities do 
    collection do
      get :search
      # get :filterBySelect
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get  'temporary', to: 'users#new'
  post 'temporary', to: 'users#temporary'


  get  'info0', to: 'users#info0'
  post 'info0', to: 'users#verify'
  patch 'info0', to: 'users#verify'

  get  'info', to: 'users#info'
  post 'info', to: 'users#addinfo'
  patch 'info', to: 'users#addinfo'
 
  resources :sessions
  #手机&验证码登录过程 login->login2->完成
  get    'login',   to: 'sessions#new'  
  post   'login',   to: 'sessions#create'
  get    'login2',   to: 'sessions#new2'
  post 'login2', to: 'sessions#create2'
  patch 'login2', to: 'sessions#create2'
  #手机&密码登录过程 login3
  get    'login3',   to: 'sessions#new3'
  post   'login3',   to: 'sessions#create3', as: 'login_3' 
  #get ':controller(/:action(/:id))'


  # 活动相关路由begin

  resources :activities
  get '/new_activity', to: 'activities#new' # 用于创建活动
  post '/create_activity', to: 'activities#create' 
  # 修改活动没有创建具名路由
  post '/update_activity/:id', to: 'activities#update'  # 用于修改活动内容表单，基于post请求而不是默认的patch请求
  get '/destroy_activity/:id', to: 'activities#destroy' # 用于删除活动
  get '/nc_user_error', to: 'activities#not_correct_user', as: 'nc_user' # 用于没有权限时的错误警告，具名路由nc_user_path
  get '/ac_error', to: 'activities#ac_error_occured', as: 'ac_error' # 用于没有权限时的错误警告，具名路由nc_user_path
  
  # 活动相关路由end




  #成员路由，为加入活动的列表页面增加路由,生成具名路由following_user_path
  resources :users do
    member  do
      get :following
    end
  end

  #生成具名路由followers_activity_path
  resources :activities do
    member do
      get :followers
    end
  end
  
  #为relationships资源创建路由
  resources :relationships, only: [:create, :destroy]

  #个人页具名路由
  get '/my_page', to: 'my_page#home' # 用于创建活动
  get '/my_page_info', to: 'my_page#showMyInfo' # 用于创建活动
  get '/my_page_activities', to: 'my_page#showMyActivities' # 用于创建活动
  get '/my_page_activities_joined', to: 'my_page#showMyActivitiesJoined' # 用于创建活动


end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower_user, class_name: "User"
    belongs_to :followed_act, class_name: "Activity"
    validates :follower_user_id, presence: true
    validates :followed_act_id,  presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only:[:create]
  # GET /relationships
  # GET /relationships.json
  def index
    @relationships = Relationship.all
  end

  # GET /relationships/1
  # GET /relationships/1.json
  def show
  end

  # GET /relationships/new
  def new
    @relationship = Relationship.new
  end

  # GET /relationships/1/edit
  def edit
  end

  # POST /relationships
  # POST /relationships.json
=begin
  def create
    @relationship = Relationship.new(relationship_params)

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to @relationship, notice: 'Relationship was successfully created.' }
        format.json { render :show, status: :created, location: @relationship }
      else
        format.html { render :new }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  #创建关系，使用户加入活动
  def create
    #使用隐藏域提交的followed_act_id查找活动
    @activity = Activity.find(params[:followed_act_id])
    #当前用户加入活动
    @current_user = User.find_by(usermobile: session[:mobile])
    @current_user.follow(@activity)
    #使用 respond_to 方法，根据请求的类型生成合适的响应
    respond_to do |format|
      #重定向至活动资料页面
      format.html { redirect_to @activity}
      format.js
    end
  end


  # PATCH/PUT /relationships/1
  # PATCH/PUT /relationships/1.json
  def update
    respond_to do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { render :show, status: :ok, location: @relationship }
      else
        format.html { render :edit }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json

  #用户退出activity活动
  def destroy
    #查找关系中“被加入”的活动
    @activity = Relationship.find(params[:id]).followed_act
    #退出活动
    @current_user = User.find_by(usermobile: session[:mobile])
    @current_user.unfollow(@activity)
    respond_to do |format|
      #重定向至活动资料页面
      format.html { redirect_to @activity }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relationship
      @relationship = Relationship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def relationship_params
      params.require(:relationship).permit(:follower_user_id, :followed_act_id)
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.erb
<%= form_with(model: relationship, local: true) do |form| %>
  <% if relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
        <% relationship.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :follower_user_id %>
    <%= form.number_field :follower_user_id %>
  </div>

  <div class="field">
    <%= form.label :followed_act_id %>
    <%= form.number_field :followed_act_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/relationships/create.js.erb
<!--使用 CSS ID 查找 follow_form,修改该 DOM 对象内容为 users/unfollow 局部视图内容 -->
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

$("#followers").html('<%= @activity.followers.count %>');

app/views/relationships/edit.html.erb
<h1>Editing Relationship</h1>

<%= render 'form', relationship: @relationship %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relationships</h1>

<table>
  <thead>
    <tr>
      <th>Follower user</th>
      <th>Followed act</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relationships.each do |relationship| %>
      <tr>
        <td><%= relationship.follower_user_id %></td>
        <td><%= relationship.followed_act_id %></td>
        <td><%= link_to 'Show', relationship %></td>
        <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
        <td><%= link_to 'Destroy', relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relationship', new_relationship_path %>

app/views/relationships/new.html.erb
<h1>New Relationship</h1>

<%= render 'form', relationship: @relationship %>

<%= link_to 'Back', relationships_path %>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Follower user:</strong>
  <%= @relationship.follower_user_id %>
</p>

<p>
  <strong>Followed act:</strong>
  <%= @relationship.followed_act_id %>
</p>

<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>