config/routes.rb
Rails.application.routes.draw do

  resources :relationships
  #用户管理，活动管理
  get 'admin/show'
  get 'admin/activityshow'
  get 'admin/activity_allow'
  get 'admin/activity_fail'
  get 'admin/myActivity'
  get 'admin/createMyActivity'
  get 'admin/personal'
  get 'admin/delete'
  get 'admin/update'
  get 'sessions/new'
  resources :users

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/schoolSelect'
  get 'static_pages/filterBySelect'
  # 根路由
  root 'static_pages#home'
  # 具名路由
  get  '/help',    to: 'static_pages#help'
  get  '/schoolSelect',  to: 'static_pages#schoolSelect'
  get "/search" => "search#index", :as => "search"
  resources :activities do 
    collection do
      get :search
      # get :filterBySelect
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get  'temporary', to: 'users#new'
  post 'temporary', to: 'users#temporary'


  get  'info0', to: 'users#info0'
  post 'info0', to: 'users#verify'
  patch 'info0', to: 'users#verify'

  get  'info', to: 'users#info'
  post 'info', to: 'users#addinfo'
  patch 'info', to: 'users#addinfo'
 
  resources :sessions
  #手机&验证码登录过程 login->login2->完成
  get    'login',   to: 'sessions#new'  
  post   'login',   to: 'sessions#create'
  get    'login2',   to: 'sessions#new2'
  post 'login2', to: 'sessions#create2'
  patch 'login2', to: 'sessions#create2'
  #手机&密码登录过程 login3
  get    'login3',   to: 'sessions#new3'
  post   'login3',   to: 'sessions#create3', as: 'login_3' 
  #get ':controller(/:action(/:id))'


  # 活动相关路由begin

  resources :activities
  get '/new_activity', to: 'activities#new' # 用于创建活动
  post '/create_activity', to: 'activities#create' 
  # 修改活动没有创建具名路由
  post '/update_activity/:id', to: 'activities#update'  # 用于修改活动内容表单，基于post请求而不是默认的patch请求
  get '/destroy_activity/:id', to: 'activities#destroy' # 用于删除活动
  get '/nc_user_error', to: 'activities#not_correct_user', as: 'nc_user' # 用于没有权限时的错误警告，具名路由nc_user_path
  get '/ac_error', to: 'activities#ac_error_occured', as: 'ac_error' # 用于没有权限时的错误警告，具名路由nc_user_path
  
  # 活动相关路由end




  #成员路由，为加入活动的列表页面增加路由,生成具名路由following_user_path
  resources :users do
    member  do
      get :following
    end
  end

  #生成具名路由followers_activity_path
  resources :activities do
    member do
      get :followers
    end
  end
  
  #为relationships资源创建路由
  resources :relationships, only: [:create, :destroy]

  #个人页具名路由
  get '/my_page', to: 'my_page#home' # 用于创建活动
  get '/my_page_info', to: 'my_page#showMyInfo' # 用于创建活动
  get '/my_page_activities', to: 'my_page#showMyActivities' # 用于创建活动
  get '/my_page_activities_joined', to: 'my_page#showMyActivitiesJoined' # 用于创建活动


end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    #建立User与Relationship之间的关联，一个人可以加入多个活动，主动关系的外键为follower_user_id
    has_many :active_relationships, class_name: "Relationship",foreign_key: "follower_user_id"
    #可以使用following数组来获取当前用户加入的活动列表
    has_many :following, through: :active_relationships,source: :followed_act
    # 和活动建立一对多联系
    has_many :activities

    mount_uploader :userimage, UserimageUploader 
    validates :password, presence: true, length: { minimum: 6, maximum: 20 }
    validates :password_confirmation, presence: true, length: { minimum: 6, maximum: 20 }
    validates :usermobile, presence: true, length: { minimum: 3, maximum: 13 },uniqueness: true#手机号

    validates :usernickname, presence: true , length: { minimum: 1, maximum: 50 },uniqueness: { case_sensitive: false}#昵称   
    validates :username, presence: true , length: { minimum: 2, maximum: 50 }#真实姓名
    validates :usersex, presence: true #性别
    validates :userid, presence: true ,uniqueness: { case_sensitive: false}#学号


    validates :usercollege,  length: { minimum: 2, maximum: 50 }#学院
    validates :userintro,  length: {maximum: 100 }#个人简介

    #加入一个活动
    def follow(activity)
        self.active_relationships.create(followed_act_id: activity.id)
    end

    #退出一个活动
    def unfollow(activity)
        self.active_relationships.find_by(followed_act_id: activity.id).destroy
    end

    #判断当前用户是否加入了指定活动
    def following?(activity)
        self.following.include?(activity)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def index
    @users = User.all
  end
  # POST /users/temporary

  def temporary
    mobile=params[:user][:usermobile]#手机号
    unless User.find_by(usermobile: mobile).nil?
      flash.now[:danger] = "注册失败，已经存在该账号！"
      render 'new'
    else
      vcode=rand(1000..9999).to_s  
      session[:mobile]=mobile
      session[:vcode]=vcode
      sendvcode(mobile,vcode)#进行验证码发送的help方法，尽量不要使用，免费短信有限。。。
      redirect_to :action => 'info0'
    end
  end

  def info0
    if session[:mobile]==""
      render 'new'
    end
  end

  def verify
    unless User.find_by(usermobile: session[:mobile]).nil?
      flash.now[:danger] = "注册失败，已经存在该账号！"
      render 'new'
    end
    puts "验证码实例"+params[:user][:vcode] 
    unless session[:vcode]==params[:user][:vcode]   #验证的方法暂时注释，这个和上边的发送验证码的是关联的
      flash.now[:danger] = "注册失败，验证码错误！" 
        clearsession
        render 'new'
    else
      redirect_to :action => 'info'
    end
    
  end


  def info
    if session[:mobile]==""
      render 'new'
    end
  end

  def addinfo
     unless User.find_by(usermobile: session[:mobile]).nil? 
      flash.now[:danger] = "注册失败，已经存在该账号！"
      render 'new'
     end
     

      user = User.new()
      user.usermobile = session[:mobile]
      user.password = params[:user][:password]
      user.password_confirmation = params[:user][:password_confirmation]
      user.usernickname=params[:user][:usernickname]
      user.username=params[:user][:username]
      user.usersex=params[:user][:usersex]
      user.userid=params[:user][:userid]
      user.usercollege=params[:user][:usercollege]
      user.userbirth=params[:user][:userbirth]
      user.userintro=params[:user][:userintro]
      user.userimage="/assets/co.jpg"
      
      

      if user.save
        session[:mobile]=nil;
        puts "恭喜你，注册成功！"
        redirect_to login_path
      else
          flash.now[:danger] = "注册失败，用户信息添加错误！"
          render 'info'               
      end   
  end
  

  #通过id查询用户，并且通过following检索该用户参加的活动 
  def following
    @title = "全部活动" 
    @user  = User.find(params[:id])
    @activitys = @user.following.paginate(page: params[:page])
    render 'show_following'
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find_by(usermobile: session[:mobile])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:usermobile, :password_digest,:usernickname,
                        :username,:usersex,:userbirth,:usercollege,:userid,:userintro)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
require 'rest-client'

module UsersHelper

    def sendvcode(mobile,random) 
        puts mobile
        puts random

        url="http://106.ihuyi.com/webservice/sms.php?method=Submit"
 
        account="C23208413"
        password="75500244ec8cc451ce0e3d7922c6030b "
        mobile=mobile.to_i
        random=random.to_i      
        puts mobile
        puts random
        response = RestClient.post url, {account: account, password: password,
            mobile: mobile,content: "您的验证码是：#{random}。请不要把验证码泄露给其他人。"}

        
        puts response.code
        puts response.cookies
        puts response.headers
        puts response.body

    end


    def clearsession
        session[:vcode]=nil;
        session[:mobile]=nil;
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :usermobile %>
    <%= form.text_field :usermobile %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.username, user %>
</li>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Usermobile</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.usermobile %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/info.html.erb
<% provide(:title, '完善资料') %>





<%= form_for(:user, url: info_path,:multipart => true)  do |f| %>   
  
  <div style="margin: auto;text-align: center;margin-top: 100px"><input placeholder="请输入密码" type="text" name="user[password]" id="user_password" style="text-align: center;width:60%;height:100px;font-size: 40px;BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: solid"></div>
  <div style="margin: auto;text-align: center;margin-top: 20px"><input placeholder="请重复输入密码" type="text" name="user[password_confirmation]" id="user_password_confirmation" style="text-align: center;width:60%;height:100px;font-size: 40px;BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: solid"></div>
  <div style="margin: auto;text-align: center;margin-top: 20px"><input placeholder="请输入昵称" type="text" name="user[usernickname]" id="user_usernickname" style="text-align: center;width:60%;height:100px;font-size: 40px;BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: solid"></div>
  <div style="margin: auto;text-align: center;margin-top: 20px"><input placeholder="请输入真实姓名" type="text" name="user[username]" id="user_username" style="text-align: center;width:60%;height:100px;font-size: 40px;BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: solid"></div>
  <div style="margin: auto;text-align: center;margin-top: 20px;font-size: 40px;"><input type="radio" value="女" name="user[usersex]" id="user_usersex_女" checked="checked"  style="width:10%;height:40px;">女
      <input type="radio" value="男" name="user[usersex]" id="user_usersex_男" style="width:10%;height:40px;">男</div>
  <div style="margin: auto;text-align: center;margin-top: 20px;font-size: 40px;"><input  placeholder="生日格式：2020-06-01" type="text" name="user[userbirth]" id="user_userbirth" pattern="\d{4}-\d{2}-\d{2}"  style="text-align: center;width:60%;height:100px;font-size: 40px;BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: solid"></div>
  <div style="margin: auto;text-align: center;margin-top: 20px"><input placeholder="请输入学院" type="text" name="user[usercollege]" id="user_usercollege" style="text-align: center;width:60%;height:100px;font-size: 40px;BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: solid"></div>
  <div style="margin: auto;text-align: center;margin-top: 20px"><input placeholder="请输入学号" type="text" name="user[userid]" id="user_userid" style="text-align: center;width:60%;height:100px;font-size: 40px;BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: solid"></div>
  <div style="margin: auto;text-align: center;margin-top: 20px"><input placeholder="向别人展示一下自己吧~" type="text" name="user[userintro]" id="user_userintro" style="text-align: center;width:60%;height:100px;font-size: 40px;BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: solid"></div>    
  <div style="margin: auto;text-align: center;margin-top: 20px"><input type="submit" name="commit" value="完成" data-disable-with="完成" style="border-radius: 20px; background-color: white; color: #09a7c6;border: 2px solid #09a7c6;width:60%;font-size: 40px;height:100px;"></div>
  

<% end %>


    

<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/users/info0.html.erb
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
<script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<% provide(:title, '验证码验证') %>
<!--上部-->
<div style="width:100%;height: 600px;background: #09a7c6">
  <img src="/assets/logo" alt="logo" width=450px  height=450px style="margin-top: 100px;margin-left: 270px"/> 
</div>
<!--表单部分-->


<%= form_for(:user,  url:  info0_path) do |f| %>    
  <div style="margin: auto;text-align: center;margin-top: 100px"><input placeholder="请输入验证码" type="text" name="user[vcode]" id="session_vcode" style="width:90%;height:100px;font-size: 50px;BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: solid"></div>
  <div style="margin: auto;text-align: center;margin-top: 20px"><input type="submit" name="commit" value="确定" data-disable-with="确定" style="border-radius: 20px;background-color: #09a7c6;width:60%;font-size: 50px;height:100px;"></div> 
<% end %>
  




<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/users/new.html.erb
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
<script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<% provide(:title, '注册') %>
<!--上部-->
<div style="width:100%;height: 600px;background: #09a7c6">
 <div style="float: right;width: 10%;font-size: 40px;margin-top: 30px;margin-right: 30px" ><%= link_to( "登陆", new_session_path,class: "text-white") %> </div>
  <img src="/assets/logo" alt="logo" width=450px  height=450px style="margin-top: 100px;margin-left: 270px"/> 
</div>
<!--表单部分-->


<%= form_for(:user,  url:  temporary_path) do |f| %>    
  <div style="margin: auto;text-align: center;margin-top: 100px"><input placeholder="请输入手机号" type="text" name="user[usermobile]" id="user_usermobile" style="width:90%;height:100px;font-size: 50px;BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: solid"></div>
  <div style="margin: auto;text-align: center;margin-top: 20px"><input type="submit" name="commit" value="获取验证码" data-disable-with="获取验证码" style="border-radius: 20px;background-color: #09a7c6;width:60%;font-size: 50px;height:100px;"></div> 
<% end %>
  


<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "用户详情")%>
<%= render '/layouts/activities/header'%>
<div class="container">
<div class="row">
<div class="col-md-8 activity-show-card activity-show-card-3">

<div class="activity-notice">
  <%= notice%>
</div>

<span class="badge badge-secondary">用户页</span>

<div class="h4 alert alert-primary activity-show-background">
   <p class="activity-show-title"> 用户名 </p>
    <hr class="activity-show-line">
    <%= @user.username %>
</div>


<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">用户电话</p>
     <hr class="activity-show-line"> 
      <%= @user.usermobile %>
</div>



<!--通过点击参加活动数可以展示该用户参与的活动 -->
<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">参加活动数</p>
     <hr class="activity-show-line">
      <%= link_to @user.following.count, {:controller => "users", :action => "following"}%> 个活动
</div>

</div>
</div>
</div>

<%=render 'layouts/activities/self_footer'%>

app/views/users/show_following.html.erb
<div class="container">
<div class="row">
<div class="col-md-8 activity-show-card activity-show-card-3">

<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= link_to @user.username, @user %></h1>
      <span><%= @user.following.count %>个活动</span>
    </section>
    <section class="stats">
      <%= render 'share/stats_user' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render '/layouts/activities/header'%>
    <% if @activitys.any? %>
      <ul class="activitys followed">
        <%= render @activitys %>
      </ul>
    <% end %>
  </div>
</div>


</div>
</div>
</div>

<%=render 'layouts/activities/footer'%>