config/routes.rb
Rails.application.routes.draw do

  resources :relationships
  #用户管理，活动管理
  get 'admin/show'
  get 'admin/activityshow'
  get 'admin/activity_allow'
  get 'admin/activity_fail'
  get 'admin/myActivity'
  get 'admin/createMyActivity'
  get 'admin/personal'
  get 'admin/delete'
  get 'admin/update'
  get 'sessions/new'
  resources :users

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/schoolSelect'
  get 'static_pages/filterBySelect'
  # 根路由
  root 'static_pages#home'
  # 具名路由
  get  '/help',    to: 'static_pages#help'
  get  '/schoolSelect',  to: 'static_pages#schoolSelect'
  get "/search" => "search#index", :as => "search"
  resources :activities do 
    collection do
      get :search
      # get :filterBySelect
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get  'temporary', to: 'users#new'
  post 'temporary', to: 'users#temporary'


  get  'info0', to: 'users#info0'
  post 'info0', to: 'users#verify'
  patch 'info0', to: 'users#verify'

  get  'info', to: 'users#info'
  post 'info', to: 'users#addinfo'
  patch 'info', to: 'users#addinfo'
 
  resources :sessions
  #手机&验证码登录过程 login->login2->完成
  get    'login',   to: 'sessions#new'  
  post   'login',   to: 'sessions#create'
  get    'login2',   to: 'sessions#new2'
  post 'login2', to: 'sessions#create2'
  patch 'login2', to: 'sessions#create2'
  #手机&密码登录过程 login3
  get    'login3',   to: 'sessions#new3'
  post   'login3',   to: 'sessions#create3', as: 'login_3' 
  #get ':controller(/:action(/:id))'


  # 活动相关路由begin

  resources :activities
  get '/new_activity', to: 'activities#new' # 用于创建活动
  post '/create_activity', to: 'activities#create' 
  # 修改活动没有创建具名路由
  post '/update_activity/:id', to: 'activities#update'  # 用于修改活动内容表单，基于post请求而不是默认的patch请求
  get '/destroy_activity/:id', to: 'activities#destroy' # 用于删除活动
  get '/nc_user_error', to: 'activities#not_correct_user', as: 'nc_user' # 用于没有权限时的错误警告，具名路由nc_user_path
  get '/ac_error', to: 'activities#ac_error_occured', as: 'ac_error' # 用于没有权限时的错误警告，具名路由nc_user_path
  
  # 活动相关路由end




  #成员路由，为加入活动的列表页面增加路由,生成具名路由following_user_path
  resources :users do
    member  do
      get :following
    end
  end

  #生成具名路由followers_activity_path
  resources :activities do
    member do
      get :followers
    end
  end
  
  #为relationships资源创建路由
  resources :relationships, only: [:create, :destroy]

  #个人页具名路由
  get '/my_page', to: 'my_page#home' # 用于创建活动
  get '/my_page_info', to: 'my_page#showMyInfo' # 用于创建活动
  get '/my_page_activities', to: 'my_page#showMyActivities' # 用于创建活动
  get '/my_page_activities_joined', to: 'my_page#showMyActivitiesJoined' # 用于创建活动


end

app/models/activity.rb
class Activity < ApplicationRecord

    # 建立起与用户的联系，外键默认是user_id这种形式，手动设置为UserId
    belongs_to :user, class_name: "User", foreign_key: "UserId"
    validates :UserId, presence: {message: "用户id不能为空"}  #用户id
    # 在查找一堆活动时，默认按照创建时间倒序的方式展示
    default_scope -> {order(created_at: :desc)}

    validates :AcStatus, presence: {message: "活动状态不能为空"} #活动状态
    validates :AcClass, presence: {message: "活动类别不能为空"} #活动类别
    validates :AcTitle, presence: {message: "活动标题不能为空"}, length: {maximum: 50, message: "活动标题不能超过50个字符"} #活动标题
    validates :AcSitu, presence: {message: "地点不能为空"} #活动地点
    validates :AcStartTime, presence: {message: "活动开始时间不能为空"} #活动开始时间
    validates :AcEndTime, presence: {message: "活动截止时间不能为空"} #报名截止时间
    validates :AcCount, presence: {message: "报名人数不能为空"} #报名人数
    validates :AcDura, presence: {message: "活动时长不能为空"} #活动时长
    validates :AcIsPra, presence: {message: "未设置活动是否私密"} #活动是否私密
    # 私密活动密码允许为空，但只能是3位数字
    validates :AcPass, allow_blank: true, length: {is: 4, message: "密码应当设置为4位数字"}, 
        numericality: { only_integer: true, message: "密码只能是3位数字" } 
    validates :AcIntro, presence: {message: "活动简介不能为空"}, length: {maximum: 1000, message: "活动简介不能超过1000个字符"} #活动简介

    # 暂时未实现图片功能
    # # 使用mount_uploader方法把图片和模型关联起来
    mount_uploader :picture, PictureUploader
    validate  :picture_size

    # 验证图片上传的大小
    def picture_size
        puts "function==picture_size:#picture.size"
        # 如果图片大于5MB
        if picture.size>5.megabytes
            # 就向errors合集中添加一个自定义的消息
            errors.add(:picture,"should less than 5MB")
        end
    end
    
    has_many :passive_relationships, class_name: "Relationship",foreign_key: "followed_act_id"
    #可使用followers数组获取加入了当前活动的用户列表
    has_many :followers, through: :passive_relationships,source: :follower_user

    #判断指定用户是否加入了当前活动
    def followed?(user)
        self.followers.include?(user)
    end

    # 当活动为私密时，用该方法可以验证输入口令是否和@activity.AcPass密码匹配
    def correct_activity_password?(token)
        if self.AcIsPra == 1 && self.AcPass.to_i == token.to_i
            return true
        else
            return false
        end
    end

    # 用来显示活动图片的名称
    def show_picture_name
        name = self.picture.to_s.split("/")
        return name[-1]
    end 
    # 分类筛选多个条件组合筛选
    def self.like_any(fields, values)
        where fields.map { |field|
          values.map { |value|
            arel_table[field].matches("%#{value}%")
          }.inject(:or)
        }.inject(:or)
      end

    
end

app/controllers/activities_controller.rb
require 'time'
class ActivitiesController < ApplicationController


  # 回调函数，在执行下面的4个方法时都会根据传值设定好@activity
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  # 出现csrf报错时的处理
  skip_before_action :verify_authenticity_token
  # 要判断是否是活动的拥有者或是管理员
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  # 还要有logged_in_user的判断，限定在动作之前登录才行
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy, :create, :new]
  # 检查活动是否已经到了截止时间，如果是则活动终止，并且不可以再次编辑，显示相应内容
  before_action :check_time, only: [:show, :edit, :update]

  # GET /activities
  # GET /activities.json

  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
 
  def show
  end

  # GET /activities/new
 
  def new
  end

  # GET /activities/1/edit

  def edit
    # 如果没有修改权限或者活动已经截止，却能执行到这里，则跳转到异常处理界面
    if @isCorrectUser == 0 || @activityIsEnded == 1 || @activity.AcStatus != "1"
      redirect_to nc_user_path
      return
    end
    # 将开始时间和截止时间显示在页面上
    # 数据库中datetime是2003-01-01 00:00:00 UCT的格式
    # 这里要把数据库中的格式转换成：2003-01-01T00:00:00的形式才能显示，使用实例变量传入视图
    tmp0=@activity.AcStartTime.to_s.split()
    @start_time=tmp0[0] + 'T' + tmp0[1]
    tmp1=@activity.AcEndTime.to_s.split()
    @end_time=tmp1[0] + 'T' + tmp1[1]
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    # 这里应当考虑用current_user.activities.new()来创建活动
    user = current_user
    @activity.UserId = user.id # 这里应当改为当前用户id，目前以id为1的用户来进行测试
    @activity.AcStatus = "1" # 活动创建后即表示正在进行中，值为1
    puts "#{@activity.picture}"
    # 至于AcId可以考虑除去，因为使用的是id作为主键
    puts "#{@activity.UserId}"
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: '活动创建成功！' }
        format.json { render :show, status: :created, location: @activity }
      else
        puts "!!创建失败，原因:#{@activity.errors.messages}"
        format.html { render 'shared/_error' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  # 修改时先经过edit动作，返回edit视图，将修改提交到此动作
  def update
    # 如果没有修改权限或者活动已经截止，却能执行到这里，则跳转到异常处理界面
    if @isCorrectUser == 0 || @activityIsEnded == 1|| @activity.AcStatus != "1"
      redirect_to nc_user_path
      return
    end
    # 每次更改后都要设置为正在进行
    activity_params_extends = activity_params
    activity_params_extends[:AcStatus] = "1"
    puts "!! activity_params = #{activity_params}"
    puts "!! activity_params_extends = #{activity_params_extends}"
    respond_to do |format|
      if @activity.update(activity_params_extends)
        format.html { redirect_to @activity, notice: '活动修改成功!' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render 'shared/_error' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  # 删除后应当跳转到当前用户的活动列表页，并提示notice
  def destroy
    if @isCorrectUser == 0
      redirect_to nc_user_path
      return
    end
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: '活动删除成功！' }
      format.json { head :no_content }
    end
  end

  # 没有权限时错误警告
  def not_correct_user
    render 'shared/_nc_user_error'
  end

  # 活动不存在出错
  def ac_error_occured
    render 'shared/_ac_error'
  end

  def followers
    @title = "当前成员"
    #通过id查询活动，并检索该活动的followers列表
    @activity = Activity.find(params[:id])
    @users = @activity.followers.paginate(page: params[:page])
    render 'show_followers'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      find_id = params[:id]
      # 首先检查相应id的活动是否存在
      puts "#{find_id}"
      all_activities = Activity.all
      isFounded = 0
      all_activities.each do |a|
        if find_id.to_i == a.id.to_i
          isFounded = 1
        end
      end
      puts "---#{isFounded}"

      if isFounded == 0
        redirect_to ac_error_path
        return
      end

      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:UserId, :AcStatus, :AcClass, :AcTitle, :AcSitu, :AcStartTime, :AcEndTime, :AcCount, :AcDura, :AcIsPra, :AcPass, :AcIntro, :picture)
    end

    # 判断是否是活动拥有者或管理员
    def correct_user
      a = Activity.find(params[:id])
      # 有了current_user功能后可以使用,先设置为当前用户值为1
      user = current_user # 在application中已经include sessions_helper了
      puts "***当前用户的手机号为: #{user.usermobile}***"
      puts "***a.UserId为: #{a.UserId}***"
      puts "***user.id为: #{user.id}***"
      # @isCorrectUser = 1 
      if a.UserId.to_i == user.id.to_i
         @isCorrectUser = 1
      else
         @isCorrectUser =  0 # 因为show动作允许不是owner，所以不用设置异常页
      end
      puts "***@isCorrectUser = #{@isCorrectUser}***"
    end

    # 根据当前时间设置活动是否已经结束的状态
    def check_time
      ac = Activity.find(params[:id])
      puts "#{ac.AcStatus}"
      endTimeStr = ac.AcEndTime.strftime('%Y-%m-%d %H:%M:%S')
      puts "***endtime = #{ac.AcEndTime}, formatStr = #{endTimeStr}"
      nowTime = Time.now
      nowTimeFmtStr = nowTime.strftime('%Y-%m-%d %H:%M:%S')
      puts "当前时间为: #{nowTime}, formatStr = #{nowTimeFmtStr}"
      eTime = Time.parse(endTimeStr)
      nTime = Time.parse(nowTimeFmtStr)
      puts "eTime = #{eTime}, nTime = #{nTime}"
      # 活动已经结束则该值为1，否则为0
      if eTime <= nTime
        @activityIsEnded = 1
        # 设置活动状态结束 3
        ac.update_attribute(:AcStatus, "3")
      else
        @activityIsEnded = 0
      end
      puts "ended? #{@activityIsEnded},status = #{ac.AcStatus}"
    end

  end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<li>
    <div class="h4 alert alert-primary activity-show-background">
        <hr class="activity-show-line">
        <%= link_to activity.AcTitle, activity %>
    </div>
</li>

app/views/activities/_follow.html.erb
<!--加入活动-->
<!--构建一个新的active_relationships关系，向Relationships的create动作发送一个POST请求-->

<%= form_for(current_user.active_relationships.build,remote: true) do |f| %>
  <!--将followed_act_id隐藏在表单中，但浏览器不显示，在relationships_controller中要用followed_act_id去查找相应活动-->
  <div><%= hidden_field_tag :followed_act_id, @activity.id %></div>
  <%= f.submit "加入活动", class: "btn btn-primary" %>
<% end %>

app/views/activities/_form.html.erb
<style type="text/css">
</style>

<script type="text/javascript">

function load(x) {
// var input = document.getElementsByName("activity[AcIsPra]");  
  console.log(x.value);
  var ac_pass_field = document.getElementById("ac_pass");
  console.log("ac: r= " + ac_pass_field.required);
  if(x.value == 1) {
    ac_pass_field.required = true;  //当选择是时密码不能为空
    ac_pass_field.disabled = false;
  } else if(x.value == 0) {
    ac_pass_field.required = false;
    ac_pass_field.value = ""; 
    ac_pass_field.disabled = true;
  }
};
</script>

<%# 这里会跳转到 /activities，即 post请求的create动作上 %>

<form action="/create_activity" method="post" enctype="multipart/form-data">

<div class="container">
<div class="row">
<div class="col-md-8">

<div class="btn btn-secondary btn-lg active btn-sm" role="button"  aria-pressed="true">
    <%= link_to "返回", :back,:style=>"color:white"%>
</div>
<!--<a href="<%= activities_path%>" class="btn btn-secondary btn-lg active btn-sm" role="button"  aria-pressed="true">返回</a>-->

<br>
<br>


   <div class="form-group">
      <label for="ac_title">活动标题（不超过50个字符）</label>
      <input name="activity[AcTitle]" id="ac_title" class="form-control" maxlength="50" />
  </div>

  <div class="form-group">
      <label for="ac_title">活动地点</label>
      <input name="activity[AcSitu]" id="ac_situ" class="form-control" required/>
  </div>


  <div class="form-group">
    <label for="ac_class">活动类别</label>
    <select id="ac_class" name="activity[AcClass]" class="form-control" required >
      <option>旅游</option>
      <option>运动</option>
      <option>聚餐</option>
      <option>桌游</option>
      <option>讨论</option>
      <option>讲座</option>
      <option>娱乐</option>
    </select>
  </div>


    <div class="form-group">
      <label for="ac_start_time">开始时间</label>
      <input name="activity[AcStartTime]" id="ac_start_time" class="form-control" type="datetime-local" required/>
  </div>

  <div class="form-group">
    <label for="ac_dura">活动时长</label>
    <input id="ac_dura" class="form-control" type="number" name="activity[AcDura]" min="0.1" max="1024" step="0.1" placeholder="单位：小时" required/> 
  </div>


  <div class="form-group">
    <label for="ac_count">活动人数（不超过100人）</label>
    <input id="ac_count" class="form-control" type="number" name="activity[AcCount]" min="1" max="100" step="1" placeholder="单位：人" required/> 
  </div>

  <div class="form-group">
      <label>是否设为私密</label><br>
      <input class="form-radio" name="activity[AcIsPra]" type="radio" id="ac_is_pra" value="1" onclick="load(this)"/>
      <label for="ac_is_pra"><font color="#b06ab3">是</font></label>
      <input class="form-radio" name="activity[AcIsPra]" type="radio" id="ac_is_not_pra" value="0" checked onclick="load(this)"/>
      <label for="ac_is_not_pra"><font color="#b06ab3">否</font></label>
  </div>

  <div class="form-group">
    <label for="ac_pass">私密活动口令（活动口令只能由4位数字组成）</label>
    <input name="activity[AcPass]" id="ac_pass" class="form-control" type="password" disabled/>
  </div>



  <div class="form-group">
  <label for="ac_intro">活动简介</label>
  <textarea id="ac_intro" class="form-control" aria-label="With textarea" name="activity[AcIntro]" rows="10" maxlength="1000" required></textarea>
  </div>

  <br>
  <div class="form-group">
      <label for="ac_end_time">报名截止时间</label>
      <input name="activity[AcEndTime]" id="ac_end_time" class="form-control" type="datetime-local" required/>
  </div>

  <br/>
  <div class="custom-file">
    <input type="file" name="activity[picture]" class="custom-file-input" id="ac_picture" accept="image/png, image/jpeg, image/gif, image/jpg">
    <label class="custom-file-label" for="customFile">上传图片</label>
  </div>
  <br/>
  <br/>
  <div class="actions">
    <p style="text-align:center">
    <input class="btn-activity-hover color-9" type="submit" name="commit" value="提交活动">
    </p>
  </div>

</div>
</div>

</form>

<script type="text/javascript"> 
// 在客户端的对图片检查的另一个措施
// 检查图片的尺寸，图片太大就会跳出一个提示框
$('#ac_picture').bind('change',function(){
  console.log("我在执行检查图片大小的函数");
  var size_in_megabytes = this.files[0].size/1024/1024;
  console.log(size_in_megabytes + "MB");
  if(size_in_megabytes > 5){
    alert('只能上传5MB以下大小的图片，请重新选择!');
  }
  var picture_name = this.files[0].name;
  if (!picture_name.match(/.jpg|.gif|.png|.jpeg/i)){
      return alert("您上传的图片格式不正确，请重新选择！");
  }
  console.log(picture_name);
});
</script>

app/views/activities/index.html.erb
<%# 移动端需要增加的 %>
<meta name="App-Config" content="fullscreen=yes,useHistoryState=yes,transition=yes">
<meta content="yes" name="apple-mobile-web-app-capable">
<meta content="yes" name="apple-touch-fullscreen">
<meta content="telephone=no,email=no" name="format-detection">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">
<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->

<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>活动ID</th>
      <th>发起人ID</th>
      <th>活动状态</th>
      <th>活动类别</th>
      <th>活动标题</th>
      <th>活动地点</th>
      <th>开始时间</th>
      <th>报名截止时间</th>
      <th>活动人数</th>
      <th>活动时长</th>
      <th>是否私密</th>
      <th>私密活动密码</th>
      <th>活动简介</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.id %></td>
        <td><%= activity.UserId %></td>
        <td><%= activity.AcStatus %></td>
        <td><%= activity.AcClass %></td>
        <td><%= activity.AcTitle %></td>
        <td><%= activity.AcSitu %></td>
        <td><%= activity.AcStartTime.strftime('%Y-%m-%d %H:%M:%S')%></td>
        <td><%= activity.AcEndTime.strftime('%Y-%m-%d %H:%M:%S') %></td>
        <td><%= activity.AcCount %></td>
        <td><%= activity.AcDura %></td>
        <td><%= activity.AcIsPra %></td>
        <td><%= activity.AcPass %></td>
        <td><%= activity.AcIntro %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <%# 下面的方法废弃 %>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '返回首页', root_path %>
<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<% provide(:title, "创建一个新活动")%>
<%= render '/layouts/activities/header'%>

<br>


<%# <%= link_to '返回', activities_path %> 

<%= render 'form', activity: @activity %>
<%= render '/layouts/activities/footer' %>

app/views/activities/show.html.erb
<% provide(:title, "活动详情")%>
<%= render '/layouts/activities/header'%>

<script type="text/javascript">
    function confirm_destroy(id) {
        console.log(id);
        var select = window.confirm("确认删除当前活动吗？");
        if(select == true) {
            window.location ="/destroy_activity/" + id;
        }
    }
</script>


<div class="container">
<div class="row">
<div class="col-md-8 activity-show-card activity-show-card-3">

<div class="activity-notice">
  <%= notice%>
</div>


<span class="badge badge-secondary">活动页</span>
<div class="btn btn-secondary btn-lg active btn-sm pull-right" role="button"  aria-pressed="true">
    <%= link_to "返回", :back,:style=>"color:white"%>
</div>

<div class="h4 alert alert-primary activity-show-background">
   <p class="activity-show-title"> 活动标题 </p>
    <hr class="activity-show-line">
    <%= @activity.AcTitle %>
</div>

<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">活动地点</p>
     <hr class="activity-show-line">
     <%= @activity.AcSitu %>
</div>

<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">活动类别</p>
     <hr class="activity-show-line"> 
      <%= @activity.AcClass %>
</div>

<%# 应当修改为用户名 %>
<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">发起人id</p> 
     <hr class="activity-show-line">
     <%= @activity.UserId %>
</div>


<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">活动状态</p> 
     <hr class="activity-show-line">
    <% status = @activity.AcStatus %>
    <% puts "当前活动状态为： = #{@activity.AcStatus}"%>
    <% if status == "0" %>
    <p style="color:darkmagenta;">
    <%= "正在审核中..."%>
    </p>
    <% elsif status == "1"%>
    <p style="color:green;">
    <%= "正在进行..." %>
    </p>
    <% elsif status == "2"%>
    <p style="color:red;">
    <%= "审核失败,活动终止,您可以尝试重新更改后提交" %>
    </p>
    <% elsif status == "3"%>
    <p style="color:palevioletred;">
    <%= "报名已结束" %>
    <%end%>
</div>


<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">活动时间</p> 
     <hr class="activity-show-line">
    <%= @activity.AcStartTime.strftime('%Y-%m-%d %H:%M:%S') %>
</div>

<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">报名截止时间</p> <hr class="activity-show-line">
     <%= @activity.AcEndTime.strftime('%Y-%m-%d %H:%M:%S') %>
</div>

<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">活动目标人数</p>
     <hr class="activity-show-line">
      <%= @activity.AcCount%> 人
</div>

<!--通过点击活动人数可以跳转到参与者页面 -->
<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">当前活动人数</p>
     <hr class="activity-show-line">
      <%= link_to @activity.followers.count, {:controller => "activities", :action => "followers"}%> 人
</div>

<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">活动时长</p>
     <hr class="activity-show-line">
      <%= @activity.AcDura %> 小时
</div>

<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">是否私密</p>  
     <hr class="activity-show-line">
    <% isPra = @activity.AcIsPra %>
    <% if isPra == 0 %>
    <%= "否"%>
    <% elsif isPra == 1%>
    <%= "是"%>
    <%end%>
</div>

<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">活动简介</p> 
     <hr class="activity-show-line">
      <%= @activity.AcIntro %>
</div>


<% if @activity.picture? %>
<div class="h4 alert alert-primary activity-show-background">
    <p class="activity-show-title">图片介绍</p> 
     <hr class="activity-show-line">
     <div class="activity-show-image">
      <img src=<%= @activity.picture.url%> style="height:190px;width:190px;align:center;"/>
    </div>
</div>
<% end%>

<div class="btn btn-secondary btn-lg active btn-sm" role="button"  aria-pressed="true">
    <%= link_to "返回", :back,:style=>"color:white"%>
</div>
<!--<a href="<%= activities_path%>" class="btn btn-secondary btn-lg active btn-sm" role="button"  aria-pressed="true">返回</a>-->
<%#用户浏览自己创建的活动时,并且活动没有到截止时间，显示“返回，编辑，删除” #%>
<% if @isCorrectUser == 1 && @activityIsEnded == 0%>
<a href="<%= edit_activity_path(@activity)%>" class="btn btn-secondary btn-lg active btn-sm" role="button" aria-pressed="true" style="align:right">编辑</a>
<a class="btn btn-secondary btn-lg active btn-sm" role="button"  aria-pressed="true" onclick="confirm_destroy(<%= @activity.id %>)">删除</a>
<%# 现在改为不经过审核即可发布处于进行状态，状态值为1，其它用户可以加入状态值为1的活动 %>
<% elsif (@isCorrectUser == 0 && @activityIsEnded == 0 && @activity.AcStatus == "1")%>
<%# 

---- 判断当前用户是否加入的功能，在follow_form中已经实现
%>

<%# 如果不是活动拥有者，并且活动已经审核成功正在进行中，则显示可以加入按钮 %>
<div style="margin-top:10px">
<%= render 'follow_form' if logged_in? %>
<div>
<% end%>
<br/>

</div>
</div>
</div>



<%=render 'layouts/activities/self_footer'%>